### PR TITLE
Adding XML link into availability info

### PR DESCRIPTION
**Pull request by EnginEren**
Hi Marian,

I did some changes in the code so that we see now XML link in the availability info. I attached screenshots.

I did the changes in another branch called "Dev". Therefore, now I'm creating merge request so that you look at the changes (and screenshots) and comment about it. I did not put system into production, when you approve this pull request, I will go ahead and put system into production.

Best,
Engin 
screenshot 2016-04-10 22 10 36
screenshot 2016-04-10 22 11 16

### CODE REVIEW

**Comment by EnginEren** [comment]
Just one thing : You need to tunnel to CERN's network to be able to open the XML link [1] 

[1] http://vocms037.cern.ch/sls/xrdfed_kibana/testEngin/XRDFED_CMS-US-UNL.xml

**Comment by zvada** [comment]
OK, seems fine to me. How does this behave when one clicks on previously failed test? I guess failed test .xml we save to different location before new .xml is generated from cron. Any suggestion to solve it and have link for saved file available as well? Or, simply we could add path where they are stored and one should browse through. What do you think?

**Comment by EnginEren** [comment]
Yes, it is instantaneous. Meaning if we looking at XML (via tunneling to CERN) and problem still persists, it is fine. However, as you said, in the case that one has to look at the error happened yesterday (or even 1hour before), he/she should look "saved" xml where it is stored. I should add path where we store.

**Comment by zvada** [comment]
Yes, please, that's what I meant at the beginning, too - add also path where we store them. Thanks.

**Comment by EnginEren** [comment]
Hi Marian,

I added the path of failed XMLs. Please look at screenshot. 
screenshot 2016-04-21 14 29 24

**Comment by zvada** [comment]
Looks good to me!

**Comment by EnginEren** [comment]
Thanks Marian, I'm putting the changes into production.

**Pull request merged**
